CREATE TABLE llm_history (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             provider VARCHAR(50) NOT NULL,
                             model VARCHAR(100) NOT NULL,

                             input_tokens INT NOT NULL,
                             output_tokens INT NOT NULL,
                             total_tokens INT NOT NULL,

                             estimated_cost DECIMAL(12, 6) NOT NULL,

                             cached BOOLEAN NOT NULL,

                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_llm_history_created_at ON llm_history (created_at);
CREATE INDEX idx_llm_history_provider ON llm_history (provider);